fail_fast: true
exclude: ^docs/|/migrations/
default_stages:
  - pre-commit

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \w+\.(drawio|svg|html)$
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-added-large-files

  - repo: 'https://github.com/commitizen-tools/commitizen'
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages:
          - prepare-commit-msg

  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - '--py312-plus'

  - repo: 'https://github.com/adamchainz/django-upgrade'
    rev: 1.24.0
    hooks:
      - id: django-upgrade
        args:
          - '--target-version'
          - '5.1'

  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.11.2
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
